/**
 * This header is generated by class-dump-z 0.1-11s.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSSystemConfiguration.h"
#import "PSControlTableCell.h"
#import "PSEditingPane.h"
#import "PSDetailController.h"
#import "PSBundleController.h"
#import "PSViewController.h"
#import "PSSpecifier.h"
#import "PSTextViewTableCell.h"
#import "PSEditableTableCell.h"
#import "PSListItemsController.h"
#import "PSListController.h"
#import "PSSetupController.h"
#import "PSSwitchTableCell.h"
#import "PSTextEditingPane.h"
#import "PSEditableListController.h"
#import "PSTableCell.h"
#import "PSSliderTableCell.h"
//#import "PSTextView.h"
 #import "PreferencesTableCustomView.h"
#import "PSTextFieldSpecifier.h"
#import "PSConfirmationSpecifier.h"
#import "PSRootController.h"